name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry (ACR)
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_URL }}  # ACR URL (예: myregistry.azurecr.io)
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set Timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezoneLinux: Asia/Seoul

      - name: Set environment variable for TAG
        run: echo "NOW=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ secrets.AZURE_URL }}/${{ github.repository }}
          tags: ${{ env.NOW }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.AZURE_URL }}/${{ github.repository }}:${{ env.NOW }}
