name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main  # 이 부분을 필요한 브랜치로 변경하세요.

jobs:
  build-and-push:
    runs-on: self-hosted  # 셀프호스티드 러너를 사용합니다.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.AZURE_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ secrets.AZURE_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        env:
          IMAGE_NAME: your_image_name  # 이미지 이름을 변경하세요.
