name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 추가: 자체 서명된 인증서를 신뢰하도록 설정
      - name: Trust self-signed certificate
        run: |
          echo "NODE_EXTRA_CA_CERTS=/path/to/your/certificate.crt" >> $GITHUB_ENV
        # 위에서 /path/to/your/certificate.crt를 실제 인증서 경로로 바꿔주세요

      - name: Build and Push to ACR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Dockerfile
          platforms: linux/amd64
          tags: ${{ secrets.AZURE_URL }}/latest  # 'latest' 태그 사용
